# Generated by Django 3.2.5 on 2021-08-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_brand_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_no_bind',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
